### ISSUE TITLE
Cannot retrieve passwords: `org.freedesktop.NetworkManager.AgentManager.NoSecrets: No agents were available for this request.`

### ISSUE THREAD

**Issue by paternal** [fliiiix/wifi-backup#3]
Hello,
when I run `wifi backup`, I get the following exception:

~~~
Traceback (most recent call last):
  File "/home/louis/.local/lib/python3.9/site-packages/wifibackup/wifi.py", line 185, in <module>
    cli()
  File "/usr/lib/python3/dist-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3/dist-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3/dist-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3/dist-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/louis/.local/lib/python3.9/site-packages/wifibackup/wifi.py", line 21, in backup
    cons = list_connections()
  File "/home/louis/.local/lib/python3.9/site-packages/wifibackup/wifi.py", line 152, in list_connections
    if (sec_type == "wpa-psk"):
KeyError: 'psk'
~~~

I can (indirectly) trace it back to https://github.com/fliiiix/wifi-backup/blob/master/src/wifibackup/wifi.py#L116: in this function, the password cannot be retrieved, and the exception is silently ignored. If I display the exceptions, I get:

~~~
org.freedesktop.NetworkManager.AgentManager.NoSecrets: No agents were available for this request.
org.freedesktop.NetworkManager.AgentManager.NoSecrets: No agents were available for this request.
org.freedesktop.NetworkManager.Settings.Connection.SettingNotFound: Connection didn't have requested setting '802-1x'.
~~~

I run it as user (but I get the same issue as root). I installed it using pip, with python3.9.2, on Debian.

Any thought?

**Comment by fliiiix** [comment]
So I guess we are in this code path here https://github.com/fliiiix/wifi-backup/blob/594e2a0eed00ca85b5488c4f0814cce8cc891917/src/wifibackup/wifi.py#L151

where we can not access the `psk` key.

Can you log and share how `sec_type = config['802-11-wireless-security']` looks here https://github.com/fliiiix/wifi-backup/blob/594e2a0eed00ca85b5488c4f0814cce8cc891917/src/wifibackup/wifi.py#L149

(make sure to mask out secrets)

It is very possible that there are wifi setting combinations which are not really supported by this tool because I just built it to export the few types I needed.

**Comment by paternal** [comment]
Sorry about the delay…

~~~python
>>> pprint.pprint(config['802-11-wireless-security'])
{dbus.String('auth-alg'): dbus.String('open', variant_level=1),
 dbus.String('key-mgmt'): dbus.String('wpa-psk', variant_level=1)}
~~~

Is the wifi key supposed to be in this dictionary?

**Comment by fliiiix** [comment]
So the dicts look like this for me:
```
dbus.Dictionary({
  dbus.String('auth-alg'): dbus.String('open', variant_level=1), 
  dbus.String('key-mgmt'): dbus.String('wpa-psk', variant_level=1), 
  dbus.String('psk'): dbus.String('XXXXX', variant_level=1)
}, signature=dbus.Signature('sv'))
```

And as you can see I have a `psk` in there which contains a password.
I created a 0.0.4 release which does not fail if the key is missing and only print a warning. But I assume these connections  would have passwords which are then missing on import.

I think your initial assessment was right that that the underling issue stems from the `merge_secrets` where you don't have access to a secrets manager to access  passwords. So to really fix that you need to make sure you have access to the wifi passwords via dbus I guess on most systems this is done by the gnome-keyring.

**Comment by paternal** [comment]
gnome-keyring is installed… I am using Debian testing, with gnome38

**Comment by paternal** [comment]
It works with wifi-backup 0.0.4. Thanks!
Now I have to dig up the code to reuse it in script I am trying to write.

Thanks!

**Comment by fliiiix** [comment]
Happy hacking :tada:
